x-env: &env
  env_file:
    - .env

services:
  qdrant:
    <<: *env
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
