x-env: &env
  env_file:
    - .env

services:
  qdrant:
    <<: *env
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  next:
    <<: *env
    build:
      context: .
      dockerfile: packages/next/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./packages/next:/app/packages/next

  mcp-ingest:
    <<: *env
    build:
      context: .
      dockerfile: packages/mcp/ingest/Dockerfile.dev
    environment:
      QDRANT_URL: http://qdrant:6333
    volumes:
      - ./packages/mcp/ingest:/app/packages/mcp/ingest
      - ./packages/shared:/app/packages/shared
    stdin_open: true
    tty: true
    depends_on:
      - qdrant
      # - ollama

  mcp-server:
    <<: *env
    build:
      context: .
      dockerfile: packages/mcp/server/Dockerfile.dev
    environment:
      QDRANT_URL: http://qdrant:6333
      # OLLAMA_URL: http://ollama:11434
    volumes:
      - ./packages/mcp/server:/app/packages/mcp/server
      - ./packages/mcp/ingest:/app/packages/mcp/ingest
      - ./packages/shared:/app/packages/shared
    stdin_open: true
    tty: true
    depends_on:
      - qdrant
      # - ollama

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

volumes:
  ollama_data:
