// author: Claude
import { describe, expect, test } from "bun:test";
import { contentWords, jaccardOverlap } from "@/lib/tokens";

/**
 * Anti-leakage Jaccard scoring (Phase 3, audit gap #8 — validity-critical paths
 * were untested). This primitive is what keeps a fixture honest: a query that
 * lexically echoes its fact's surface hint scores high and is regenerated, so
 * retrieval can't win by dumb word-matching. These tests pin the contract the
 * freeze-time anti-leakage summary and Stage-3 regeneration both rely on.
 */

describe("contentWords", () => {
  test("lowercases, drops stopwords and sub-3-letter tokens, keeps content words", () => {
    expect(contentWords("What is the Relay Threshold")).toEqual(["relay", "threshold"]);
  });

  test("drops digits and punctuation (letter-runs only)", () => {
    expect(contentWords("threshold = 9.5 units!!")).toEqual(["threshold", "units"]);
  });

  test("empty / stopword-only input yields no content words", () => {
    expect(contentWords("the is of to")).toEqual([]);
  });
});

describe("jaccardOverlap", () => {
  test("high overlap when the query echoes the hint's content words", () => {
    // Query reuses 'relay'+'threshold'; hint adds 'units' → 2/3 overlap.
    const score = jaccardOverlap("what is the relay threshold", ["the relay threshold units"]);
    expect(score).toBeCloseTo(2 / 3, 12);
    expect(score).toBeGreaterThan(0.4); // would be regenerated by the gate
  });

  test("low overlap when the query paraphrases (no shared content words)", () => {
    const score = jaccardOverlap("how high must the gate sit", ["the relay threshold units"]);
    expect(score).toBe(0);
    expect(score).toBeLessThan(0.4); // passes the anti-leakage gate
  });

  test("identical content words → overlap 1", () => {
    expect(jaccardOverlap("relay threshold", ["relay threshold"])).toBe(1);
  });

  test("stopword-only strings → 0 (empty union, no spurious match)", () => {
    expect(jaccardOverlap("what is the", ["the is of"])).toBe(0);
  });

  test("is symmetric in content (order of words does not matter)", () => {
    const a = jaccardOverlap("relay threshold gate", ["gate threshold relay"]);
    expect(a).toBe(1);
  });
});
